#+title emacs configuration
#+property: header-args emacs-lisp :tangle ./.emacs

* Emacs dotfile

/C-c C-v t/ to regenerate the emacs dotfile.
#+begin_src emacs-lisp
;; generated from emacs.org
#+end_src

** Package Configuration

*Melpa and package configuration*

#+begin_src emacs-lisp

(require 'package)
(add-to-list 'package-archives (cons "melpa" "https://melpa.org/packages/") t)
(package-initialize)

#+end_src

List of packages needed by this configuration.

#+begin_src emacs-lisp

(setq package-selected-packages '(
  use-package
  doom-themes
  lsp-mode
  multiple-cursors 
  all-the-icons
  powerline
  neotree
  fill-column-indicator
  bazel
  groovy-mode
  yaml
  yaml-mode
  haskell-mode
  elfeed
  json-mode
  rainbow-delimiters
  which-key
  ivy
  ivy-rich
  counsel
  treemacs
  visual-fill
  visual-fill-column))

(when (cl-find-if-not #'package-installed-p package-selected-packages)
  (package-refresh-contents)
  (mapc #'package-install package-selected-packages))

#+end_src

Use ensure to ensure package installation when use-requiered is used.

#+begin_src emacs-lisp

(require 'use-package-ensure)
(setq use-package-always-ensure t)

#+end_src


** Look and feel

#+begin_src emacs-lisp

(display-time)
(menu-bar-mode -1)
(tool-bar-mode -1)
(toggle-scroll-bar -1)
(column-number-mode 1)
(line-number-mode 1)
(setq inhibit-startup-screen t)
(setq ring-bell-function 'ignore)
(savehist-mode 1)
(global-linum-mode 1)
(global-hl-line-mode 1)
(define-key read-expression-map (kbd "TAB") #'lisp-complete-symbol)

#+end_src

*Powerline*:

#+begin_src emacs-lisp

(require 'powerline)
(powerline-default-theme)
(setq powerline-arrow-shape 'arrow)

#+end_src


*** Theme

Development mode theme:
    
#+begin_src emacs-lisp

(defun dev-mode ()
  (interactive)
  (save-excursion
    (require 'doom-themes)
    (load-theme 'doom-one t)
    (text-scale-set 0)
    (cond
     ((eq system-type 'gnu/linux)
      (set-face-attribute 'default nil :family "Hack" :height 100)
      (set-background-color "#1c2023")
      (set-foreground-color "#c7ccd1"))
     ((eq system-type 'darwin)
      (set-face-attribute 'default nil :family "Courier New" :height 140)
      (set-background-color "#121212")
      (set-foreground-color "#d8dee8")))))
;;(global-set-key (kbd "C-c r m") 'dev-mode)
      
#+end_src

Presentation mode theme:

#+begin_src emacs-lisp

(defun presentation-mode ()
  (interactive)
  (save-excursion
    (dev-mode)
    (require 'doom-themes)
    (load-theme 'doom-one-light t)
    (text-scale-set 3)))
;;(global-set-key (kbd "C-c r m") 'presentation-mode)

#+end_src


** Editor

Bindings to move around the buffers, global keysets and def alises.

#+begin_src emacs-lisp

(global-set-key "\C-l" 'goto-line)
(global-set-key (kbd "C-x <up>") 'windmove-up)
(global-set-key (kbd "C-x <down>") 'windmove-down)
(global-set-key (kbd "C-x <left>") 'windmove-left)
(global-set-key (kbd "C-x <right>") 'windmove-right)
(global-set-key (kbd "C-x C-b") 'ibuffer)

(global-unset-key (kbd "C-z"))
(fset 'yes-or-no-p 'y-or-n-p)

(defalias 'select-all 'mark-whole-buffer)

#+end_src

*Tabs:*

#+begin_src emacs-lisp

(setq-default indent-tabs-mode nil)
(setq-default c-basic-offset 4)
(setq-default py-indent-offset 4)
(setq standard-indent 4)
(setq c-default-style "linux" c-basic-offset 4)
(setq scroll-step 1)
(setq make-backup-files nil)
(setq auto-fill-mode 1)
(setq next-line-add-newlines nil)

#+end_src

*Fill column indicator*:

It draws a line at char 80, it marks with red any char after char 80.

#+begin_src emacs-lisp

(require 'fill-column-indicator)
(define-globalized-minor-mode global-fci-mode fci-mode (lambda () (fci-mode 1)))
(global-fci-mode 1)
(setq fci-rule-column 79)
(setq fci-rule-width 1)
(setq fci-rule-color "grey22")

(require 'whitespace)
(setq whitespace-line-column 80)
(setq whitespace-style '(face lines-tail))
(global-whitespace-mode 1)

#+end_src

*Rainbow delimiters*:

#+begin_src emacs-lisp

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))
  
#+end_src

Paren mode:

#+begin_src emacs-lisp

(show-paren-mode 1)
(setq show-paren-delay 0)

#+end_src

*Multiple cursors*:

#+begin_src emacs-lisp

(require 'multiple-cursors)
(global-set-key (kbd "C-c m c") 'mc/edit-lines)
(global-set-key (kbd "C->") 'mc/mark-next-word-like-this)

#+end_src

*Treemacs*:

#+begin_src emacs-lisp

(use-package treemacs
  :ensure t
  :defer t
  :init
  :config
  (progn
    (setq
     treemacs-no-png-images t))
  (treemacs-resize-icons 14)
  (dolist (face '(treemacs-root-face
                  treemacs-git-unmodified-face
                  treemacs-git-modified-face
                  treemacs-git-renamed-face
                  treemacs-git-ignored-face
                  treemacs-git-untracked-face
                  treemacs-git-added-face
                  treemacs-git-conflict-face
                  treemacs-directory-face
                  treemacs-directory-collapsed-face
                  treemacs-file-face
                  treemacs-tags-face))
    (set-face-attribute face nil :family "Courier New" :height 140)))

#+end_src



** Orgmode

/C- '/ can be used to edit source code block, same keybinding can be used to
enter and exit the mini editor (which supports syntax highlighting).

/C-c C-c/ can execute the code within the source code block.
   
This configuration limits the orgfile to 80 chars width and content is put
at the center of the buffer.

#+begin_src emacs-lisp

(defun custom/org-mode-visual-fill ()
  (setq visual-fill-column-width 80
        visual-fill-column-center-text t
        fci-mode 0
        )
  (visual-fill-column-mode 1))

(use-package visual-fill-column
  :defer t
  :hook
  (org-mode . custom/org-mode-visual-fill))

#+end_src

Visually hide the begin_src statements:

#+begin_src emacs-lisp

(setq-default prettify-symbols-alist '(("#+BEGIN_SRC" . "")
                                       ("#+END_SRC" . "-")
                                       ("#+begin_src" . "")
                                       ("#+end_src" . "-")))
(setq prettify-symbols-unprettify-at-point 'right-edge)
(add-hook 'org-mode-hook 'prettify-symbols-mode)

#+end_src

Remove emphasis markers:

#+begin_src emacs-lisp

(use-package org
  :config
  (setq org-hide-emphasis-markers t))

#+end_src

Babel configuration:

#+begin_src emacs-lisp

(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (python . t)))

#+end_src

Structured templates, these are generated on the editor by typing, e.g:
/<el + tab/

#+begin_src emacs-lisp

(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("sh" . "src shell"))
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))

#+end_src

Other org configuration:

Don't ask code-execution confirmation:

#+begin_src emacs-lisp

(setq org-confirm-babel-evaluate nil)

#+end_src

Add src lang modes to org, use this as, e.g.: /#+begin_src conf-unix/

#+begin_src emacs-lisp

(push '("conf-unix" . conf-unix) org-src-lang-modes)

#+end_src

Tangle configuration:

#+begin_src emacs-lisp

(defun custom/org-babel-tangle-config()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "some/absolute/path/emacs.org"))
    ;; let dynamic scoping?
    (let ((org-confirm-babel-evaluate-nil))
      (org-babel-table))))

(add-hook 'org-mode-hook
  (lambda ()
  (add-hook 'after-save-hook #'custom/org-babel-tangle-config)))

#+end_src


*** Mini editor

** Elfeed

This is a feed reader within emacs:

#+begin_src emacs-lisp

(setq elfeed-feeds (quote
  (("https://news.ycombinator.com/rss" tech hackernews)
   ("https://blog.tartanllama.xyz/feed.xml" programming cpp)
   ("https://linuxnewbieguide.org/feed/" tech linux))))

#+end_src

It is possible to change the default browser, e.g.:

/(setq browse-url-browser-function 'eww-browse-url)/


** Ivy

#+begin_src emacs-lisp

(use-package ivy-rich
  :init
  (ivy-rich-mode 1))
  
#+end_src


** Visual aids

*Which Key*:

This is triggered with /C-h {v,f}/, v stands for variable, f for functions, etc.

#+begin_src emacs-lisp

(use-package which-key
  :init (which-key-mode)
  :diminish which-key-mode
  :config
  (setq which-key-idle-delay 1))
  
#+end_src

*Counsel*:

#+begin_src emacs-lisp

(use-package counsel
  :bind (("M-x" . counsel-M-x)
         ("C-x b" . counsel-ibuffer)
         ("C-x C-f" . counsel-find-file)
         :map minibuffer-local-map
         ("C-r" . 'counsel-minubuffer-history))
  :config
  ;; avoid start search with ^
  (setq ivy-initial-inputs-alist nil))

#+end_src


** LSP Mode

#+begin_src emacs-lisp

(use-package lsp-mode
  :commands (lsp lsp-deferred)
  :init
  (setq lsp-keymap-prefix "C-c l")
  :config
  (lsp-enable-which-key-integration t)
  :hook (rust-mode . lsp))

(setq lsp-prefer-capf t)
(setq lsp-completion-provider :capf)
(setq lsp-completion-enable t)
#+end_src


** Language specific configuration

*** Rust

LSP rust configuration: https://emacs-lsp.github.io/lsp-mode/page/lsp-rust-rls/

- rustup update
- rustup component add rls rust-analysis rust-src

#+begin_src emacs-lisp

(use-package rust-mode
  :ensure t)

#+end_src


** Final section and comments


#+begin_src emacs-lisp

(dev-mode)

#+end_src

#+begin_src emacs-lisp

;; eof
;; below this line, there's pure garbage

#+end_src
